dihedral_name = "dih-{resid:03d}-{angid:02d}"
dihedral_def_from_atoms = "{name}: TORSION ATOMS={a1},{a2},{a3},{a4}"
deepfe_def = "dpfe: DEEPFE TRUST_LVL_1={trust_lvl_1} TRUST_LVL_2={trust_lvl_1} MODEL={model} ARG={arg}"
print_def = "PRINT STRIDE={stride} ARG={arg} FILE={file}"
restraint_def = "{name}: RESTRAINT ARG={arg} KAPPA={kappa} AT={at}"
restraint_prefix = "res"